// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/aerodynamix-redesign/CalmLibrary.tsx": () => import("../components/mockups/aerodynamix-redesign/CalmLibrary.tsx"),
  "./components/mockups/aerodynamix-redesign/CinematicArcade.tsx": () => import("../components/mockups/aerodynamix-redesign/CinematicArcade.tsx"),
  "./components/mockups/aerodynamix-redesign/Current.tsx": () => import("../components/mockups/aerodynamix-redesign/Current.tsx"),
  "./components/mockups/aerodynamix-redesign/GlassPortal.tsx": () => import("../components/mockups/aerodynamix-redesign/GlassPortal.tsx"),
  "./components/mockups/aerodynamix-redesign/PlayStudio.tsx": () => import("../components/mockups/aerodynamix-redesign/PlayStudio.tsx")
};
